---
version: '3.8'

services:
  php-apa-deb-con:
    container_name: php-apa-deb-con
    build:
      context: .
      dockerfile: .\..\..\.docker\debug\Dockerfile-windows
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: .\..\..\onn-web-eng
        target: /var/www
    working_dir: /var/www
    extra_hosts:
      - host.docker.internal:host-gateway